spring:
  application:
    name: vniia
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console